const EVENT_TYPES = {
  PIPELINE_START: 'PIPELINE_START',
  PIPELINE_SUCCESS: 'PIPELINE_SUCCESS',
  PIPELINE_FAIL: 'PIPELINE_FAIL',

  NODE_EXECUTION: 'NODE_EXECUTION',

  ARCHITECT_START: 'ARCHITECT_START',
  ARCHITECT_SUCCESS: 'ARCHITECT_SUCCESS',
  ARCHITECT_FAIL: 'ARCHITECT_FAIL',

  DEVELOPER_START: 'DEVELOPER_START',
  DEVELOPER_SUCCESS: 'DEVELOPER_SUCCESS',
  DEVELOPER_FAIL: 'DEVELOPER_FAIL',

  QA_START: 'QA_START',
  QA_SUCCESS: 'QA_SUCCESS',
  QA_FAIL: 'QA_FAIL',

  ROUTER_DECISION: 'ROUTER_DECISION'
};

module.exports = {
  EVENT_TYPES
};
